### PR TITLE
Add awesome list badge

### PR DESCRIPTION
**Pull request by CraigyDavi**
https://github.com/sindresorhus/awesome/issues/253

### CODE REVIEW

**Comment by dzharii** [comment]
Hi @CraigyDavi, 

Sorry, I cannot merge your PR because it is not related to TypeScript. 
Your next TypeScript-related contributions are welcome!

**Comment by RichardLitt** [comment]
@dzharii It's related to awesome-. Might be worth looking at the issue @CraigyDavi mentioned.

**Comment by dzharii** [comment]
@RichardLitt yes, [I've read the issue and I am not going to include their brand mark](https://github.com/sindresorhus/awesome/issues/253#issuecomment-127819875) to this repository. 
Although I have the backlink to awesome at the top of the page. I think that's enough. 
They (awesome) can always exclude the link to my list if their "brand mark" is more important than the content I am providing.

**Comment by RichardLitt** [comment]
Fair points.

**Pull request closed without merging**
