### PR TITLE
Updated "Built with TypeScript" section.

### PR DESCRIPTION
**Pull request by erymski**
Added link to VS Code repository.

### CODE REVIEW

**Comment by dzharii** [comment]
Thank you @erymski 
Wow! I didn't know Microsoft open-sourced VS Code!

**Comment by ichpuchtli** [comment]
Don't forget
- Visual Studio Online
- The new Azure Portal
- IE11/Edge Developer Tools Window (Monaco)
- WinJS Code Embed Editor (Monaco)

Reference
https://www.youtube.com/watch?v=5VbQSc-RjIU

**Comment by dzharii** [comment]
thank you @ichpuchtli,  well... the reason I am not adding this projects is those are not opensource yet, so it is not easy to use it or figure out something inside implementation. 
There is a discussion about Monaco here: 
https://github.com/Microsoft/vscode/issues/446

I hope @Microsoft will eventually open source it as a stand alone project. That's a really great editor

**Comment by ichpuchtli** [comment]
Yeah no worries. Just mentioning.

**Pull request merged**
